/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git ignore.
// It is generated by Expo; kept as a stub so `tsc` finds Expo's ambient types
// even before `expo start` regenerates it.
