#!/usr/bin/env node
// spike/native-visual/gen-tokens.mjs
// Reads src/renderer/tokens.css — the single source of truth for design
// tokens — and writes spike/swiftui-ref/MantaSpikeRef/Theme.swift, the
// generated Swift token file. Deterministic: same input in, byte-identical
// output out. No timestamp, version, or hostname is emitted.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const CSS_PATH = resolve(here, "../../src/renderer/tokens.css");
const SWIFT_PATH = resolve(here, "../swiftui-ref/MantaSpikeRef/Theme.swift");

// Swift token properties in struct declaration order. The API is fixed —
// call sites (views) must not change.
const TOKENS = [
  "canvas", "panel", "card", "raised", "inset",
  "borderSubtle", "border", "borderStrong",
  "tx1", "tx2", "tx3", "tx4",
  "accent", "accentTx", "accentSolid", "onAccent",
  "ok", "warn", "danger", "info",
  "fill", "fillActive",
];

// Tokens(...) initializer argument grouping — pure formatting only.
const GROUPS = [
  ["canvas", "panel", "card"],
  ["raised", "inset"],
  ["borderSubtle", "border", "borderStrong"],
  ["tx1", "tx2", "tx3", "tx4"],
  ["accent", "accentTx", "accentSolid", "onAccent"],
  ["ok", "warn", "danger", "info"],
  ["fill", "fillActive"],
];

const camelToKebab = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

function parseThemes(css) {
  const themes = {};
  const blockRe = /\[data-theme="(light|dark)"\]\s*\{([\s\S]*?)\}/g;
  let m;
  while ((m = blockRe.exec(css))) {
    const vars = {};
    const varRe = /--([a-zA-Z0-9-]+):\s*([^;]+);/g;
    let v;
    while ((v = varRe.exec(m[2]))) vars[v[1]] = v[2].trim();
    themes[m[1]] = vars;
  }
  return themes;
}

// CSS allows a leading-dot decimal (".035"); Swift requires a leading zero
// ("0.035"). Normalize so the emitted Swift literals always compile.
const swiftNumber = (n) => (n.startsWith(".") ? "0" + n : n);

function swiftExpr(name, value) {
  const rgba = value.match(
    /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+))?\s*\)$/,
  );
  if (rgba) {
    const [, r, g, b, a] = rgba;
    return `Color(red: ${swiftNumber(r)}/255, green: ${swiftNumber(g)}/255, blue: ${swiftNumber(b)}/255, opacity: ${swiftNumber(a)})`;
  }
  if (value.startsWith("#")) return `Color(hex: \"${value}\")`;
  throw new Error(
    `token '${name}' (value '${value}') in tokens.css is neither a hex colour nor an rgba() colour`,
  );
}

function schemeBody(themeName, vars) {
  const lines = [`    private static var ${themeName}Tokens: Tokens {`];
  for (const name of TOKENS) {
    const value = vars[camelToKebab(name)];
    if (value === undefined) {
      throw new Error(
        `token '${name}' (--${camelToKebab(name)}) has no counterpart in the ${themeName} theme of ${CSS_PATH}`,
      );
    }
    lines.push(`        let ${name}: Color = ${swiftExpr(name, value)}`);
  }
  lines.push("        return Tokens(");
  for (const group of GROUPS) {
    lines.push("            " + group.map((n) => `${n}: ${n}`).join(", ") + ",");
  }
  lines.push("        )");
  lines.push("    }");
  return lines.join("\n");
}

const css = readFileSync(CSS_PATH, "utf8");
const themes = parseThemes(css);

const out = `// GENERATED FILE — do not edit by hand.
// Generated by spike/native-visual/gen-tokens.mjs from src/renderer/tokens.css
// (the single source of truth for design tokens). Re-run the generator
// (node spike/native-visual/gen-tokens.mjs) to regenerate.

import SwiftUI

struct Tokens {
    let canvas: Color
    let panel: Color
    let card: Color
    let raised: Color
    let inset: Color
    let borderSubtle: Color
    let border: Color
    let borderStrong: Color
    let tx1: Color
    let tx2: Color
    let tx3: Color
    let tx4: Color
    let accent: Color
    let accentTx: Color
    let accentSolid: Color
    let onAccent: Color
    let ok: Color
    let warn: Color
    let danger: Color
    let info: Color
    let fill: Color
    let fillActive: Color

    static func scheme(_ scheme: ColorScheme) -> Tokens {
        switch scheme {
        case .light:
            return lightTokens
        case .dark:
            return darkTokens
        @unknown default:
            return darkTokens
        }
    }

${schemeBody("light", themes.light)}

${schemeBody("dark", themes.dark)}
}

extension Color {
    init(hex: String, opacity: Double = 1) {
        var hexSanitized = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        hexSanitized = hexSanitized.hasPrefix("#") ? String(hexSanitized.dropFirst()) : hexSanitized
        var r: UInt64 = 0, g: UInt64 = 0, b: UInt64 = 0
        var int: UInt64 = 0
        Scanner(string: hexSanitized).scanHexInt64(&int)
        let length = hexSanitized.count
        if length == 6 {
            r = (int >> 16) & 0xFF
            g = (int >> 8) & 0xFF
            b = int & 0xFF
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: opacity
        )
    }
}
`;

if (readFileSync(SWIFT_PATH, "utf8") !== out) {
  writeFileSync(SWIFT_PATH, out);
}
console.log(`wrote ${SWIFT_PATH} (${out.split("\n").length - 1} lines)`);
